### ISSUE TITLE
HTTP Error 403: FORBIDDEN

### ISSUE THREAD

**Issue by VergilGao** [ms-jpq/sync-dockerhub-readme#1]
hello, i generated an Access Token in the scope of Read, Write, Delete on dockerhub, an i used this token to sync my github readme to dockerhub, then i got an error with the following output:
```
Traceback (most recent call last):
  File "/docker_readme.py", line 83, in <module>
    main()
  File "/docker_readme.py", line 75, in main
    desc = set_repo(
  File "/docker_readme.py", line 66, in set_repo
    with urlopen(req) as resp:
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
```

**Comment by guitarrapc** [comment]
It seems like cannot update README when 2FA enabled?

See same purpose other action warning.

> https://github.com/marketplace/actions/docker-hub-readme-description-sync

**Comment by jlarmstrongiv** [comment]
I do not have 2FA enabled, and still run into this error when using my Docker Personal Access Token
